#!/usr/bin/env php
<?php

define('LARAVEL_START', microtime(true));

require __DIR__.'/vendor/autoload.php';

$app = require_once __DIR__.'/bootstrap/app.php';

$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);

exit($kernel->handle(
    $input = new Symfony\Component\Console\Input\ArgvInput,
    new Symfony\Component\Console\Output\ConsoleOutput
));
# Commit 2 - 2022-01-03 16:29:00
# Commit 39 - 2022-04-20 17:56:25
# Commit 2 - 2022-01-02 14:34:23
# Commit 39 - 2022-01-19 14:30:46
# Commit 76 - 2022-02-07 18:13:15
# Commit 113 - 2022-03-12 10:25:36
